name: Compile PDF
on:
  push:
    branches:
      - '*'
    paths:
      - 'docs/thesis/**'
jobs:
  latex-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    defaults:
      run:
        shell: bash
        working-directory: ./docs/thesis/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create the output directory
        run: mkdir out
      - name: Compilation
        uses: vinay0410/tectonic-action@master
        with:
          tex_path: 'msc_thesis.tex'
      - name: Check for successful compilation
        run: ls -la msc-thesis.pdf
      - name: Get timestamp-based tag
        id: tag
        run: echo "tag=$(date +'v%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: msc-thesis.pdf
          path: docs/thesis/*.pdf
          retention-days: 3
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.tag.outputs.tag }}
          tag_name: ${{ steps.tag.outputs.tag }}
          files: docs/thesis/*.pdf